- name: generate apt preferences for bird2 and dependencies
  template:
    src: bird/apt-preferences.j2
    dest: /etc/apt/preferences.d/98bird

- name: install bird
  apt:
    name: bird2

- name: create /var/log/bird
  file:
    path: /var/log/bird
    state: directory
    group: bird
    owner: bird

- name: create bird.log with correct permission
  file:
    path: /var/log/bird/bird.log
    state: touch
    group: bird
    owner: bird

- name: configure bird
  template:
    src: bird/bird.conf.j2
    dest: /etc/bird/bird.conf
  register: bird_conf

- name: reload bird
  service:
    name: bird
    state: reloaded
  when: bird_conf.changed

- name: deploy bird logrotate config file
  template:
    src: bird/bird.logrotate
    dest: /etc/logrotate.d/bird

- name: check for default gateway from tor
  shell: |
    set -o pipefail
    /usr/sbin/birdc show route | grep 0.0.0.0/0
  args:
    executable: /bin/bash
  retries: 30
  delay: 5
  register: result
  until: result.rc == 0
  when: ansible_virtualization_type != 'virtualbox'
