- name: Ensure nvme-cli is installed
  apt:
    name: nvme-cli
    state: present
  become: yes

- name: Identify the namespace
  command: nvme id-ns -o json "{{ block_device }}"
  become: yes
  changed_when: False
  register: nvme_namespace

- name: Deserialize id-ns output
  set_fact:
    nvme_id_ns: "{{ nvme_namespace.stdout | from_json }}"

- name: Select best LBAF in the namespace
  set_fact:
    optimal_lbaf: "{{ nvme_id_ns.lbafs | optimal_nvme_lbaf }}"

- name: Format the NVMe namespace
  command: "nvme format --lbaf={{ optimal_lbaf }} --ses=1 {{ block_device }}"
  register: nvme_format_result
  changed_when: nvme_format_result.rc == 0
  become: yes
