- import_tasks: configure-operator.yml
  become: true
  tags: [never,configure-operator]
  when: configure_operator | default(true)

- import_tasks: chef-client.yml
  become: true
  tags: [never,chef-client]

- import_tasks: adjust-ceph-pool-pgs.yml
  become: true
  run_once: true
  tags: [never,adjust-ceph-pool-pgs]

- import_tasks: ceph-destroy-osds.yml
  become: true
  tags: [never,ceph-destroy-osds]

- import_tasks: reweight-ceph-osds.yml
  become: true
  run_once: true
  tags: [never,configure-ceph,reweight-ceph-osds]

- import_tasks: set-ceph-pools-size.yml
  become: true
  run_once: true
  tags: [never,configure-ceph,set-ceph-pools-size]

- import_tasks: configure-node.yml
  become: true
  tags: [never,configure-node]

- import_tasks: format-nvmes.yml
  become: true
  tags: [never,format-nvmes]
