###############################################################################
# chef environment
###############################################################################

chef_environment:
  name: virtual
  description: Virtualized BCPC Environment
  json_class: Chef::Environment
  chef_type: environment
  override_attributes:
    bcpc:
      ceph:
        pg_num: 32
        pgp_num: 32
      cloud:
        domain: "{{ cloud_domain }}"
        fqdn: "{{ cloud_fqdn }}"
        vip: "{{ cloud_ip }}"
      dns: "{{ dns }}"
      etcd:
        host_to_cnames: "{{ etcd['host_indexes'] | etcdnode_to_cnames(cloud_domain) }}"
      grub:
        cmdline_linux:
          - net.ifnames=0
          - biosdevname=0
      networking:
        mtu: "{{ networking['mtu'] }}"
      nova:
        cpu_config:
          AuthenticAMD:
            cpu_mode: custom
            cpu_model: qemu64
            cpu_model_extra_flags: []
          GenuineIntel:
            cpu_mode: custom
            cpu_model: qemu64
            cpu_model_extra_flags: []
      ntp: "{{ ntp }}"
      openstack:
        flavors:
          enabled: true
      licenses: "{{ licenses }}"
      local_proxy: "{{ local_proxy }}"
      zones: "{{ zones }}"

###############################################################################
# chef roles
###############################################################################

chef_roles:
  - name: stubnode
    description: cloud infrastructure foundational role
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]

  - name: bootstrap
    description: bootstrap node
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::web-server]
      - recipe[bcpc::ufw]
      - recipe[bcpc::rally]
      - recipe[bcpc::rally-deploy]

  - name: etcdnode
    description: etcd node
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::etcd-member]

  - name: headnode
    description: cloud infrastructure services
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::memcached]
      - recipe[bcpc::unbound]
      - recipe[bcpc::consul]
      - recipe[bcpc::mysql]
      - recipe[bcpc::proxysql]
      - recipe[bcpc::powerdns]
      - recipe[bcpc::apache2]
      - recipe[bcpc::keystone]
      - recipe[bcpc::glance]
      - recipe[bcpc::neutron-head]
      - recipe[bcpc::placement]
      - recipe[bcpc::nova-head]
      - recipe[bcpc::cinder]
      - recipe[bcpc::horizon]
      - recipe[bcpc::heat]
      - recipe[bcpc::os-quota]
      - recipe[bcpc::flavors]
      - recipe[bcpc::watcher]

  - name: rmqnode
    description: cloud infrastructure MQ services
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::rabbitmq]

  - name: node
    description: common role for all bcpc nodes
    json_class: Chef::Role
    chef_type: role
    run_list:
      - recipe[bcpc::default]
      - recipe[bcpc::ssl]
      - recipe[bcpc::cloud-archive]
      - recipe[bcpc::postfix]
      - recipe[bcpc::common-packages]
      - recipe[bcpc::kexec]
      - recipe[bcpc::apport]
      - recipe[bcpc::etckeeper]
      - recipe[bcpc::cpupower]
      - recipe[bcpc::getty]
      - recipe[bcpc::hwrng]
      - recipe[bcpc::etcd-proxy]
      - recipe[bcpc::calico-felix]

  - name: storagenode
    description: storage node
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::ceph-osd]

  - name: storageheadnode
    description: storage infrastructure services
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::ceph-mon]
      - recipe[bcpc::ceph-mgr]
      - recipe[bcpc::ceph-pools-openstack]

  - name: worknode
    description: cloud compute services
    json_class: Chef::Role
    chef_type: role
    run_list:
      - role[node]
      - recipe[bcpc::memcached]
      - recipe[bcpc::calico-work]
      - recipe[bcpc::nova-compute]

###############################################################################
# zones
###############################################################################

zones:
  enabled: false
  partitions:
    - zone: dev
      ceph:
        client: cinder
      cinder:
        backend:
          name: ceph
          private: true
          type: ceph
          pool:
            name: volumes
      nova:
        ceph:
          pool:
            name: vms
