network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp4-overrides:
        use-routes: ETH0_USE_ROUTES
    eth1:
      addresses:
        - 172.16.0.35/31
    eth2:
      addresses:
        - 172.16.0.39/31
    eth3:
      addresses:
        - 172.16.0.43/31
    eth4:
      addresses:
        - 172.16.0.76/31
    eth5:
      addresses:
        - 172.16.0.78/31
