network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp4-overrides:
        use-routes: ETH0_USE_ROUTES
    eth1:
      addresses:
        - 172.16.0.73/31
    eth2:
      addresses:
        - 172.16.0.77/31
